/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.ConfigController;
import database.DBUtil;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Font;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.joda.time.LocalDate;
import static view.MainFrame.eif;

/**
 *
 * @author gabriel
 */
public class ConfigInternalFrame extends javax.swing.JInternalFrame {
    
    private final ConfigController configController;

    /**
     * Creates new form configInternalFrame
     */
    public ConfigInternalFrame() {
        initComponents();
        
        configController = ConfigController.getInstance();
        
        salvarBtn.setEnabled(false);
        
        bkpDiario.setSelected( configController.isSetAutoBackup() );
        
        // String last_backup = configController.getLastBackupDate();
        String last_backup = configController.getLastBackupToString();
        backupLabel.setText(last_backup);
        backupLabel.setFont(new Font("Dialog", Font.BOLD, 16));
        
        int prazo_default = configController.getPrazoDefault();
        prazoField.setText(String.valueOf(prazo_default));
        
        Double valor = configController.getAppConfigTaxaJuros();
        String s = String.format("%1$,.2f", valor);
        // String s = NumberFormat.getCurrencyInstance().format(valor);
        taxaField.setText(""+s);
       
        LocalDate date = new LocalDate(System.currentTimeMillis());
        footer.setText("© 2015 - "+ date.getYear() + " · Gabriel Dewes");
        appVersion.setText(configController.getAppVersion());
    }
    
    void openBrowser(String uri) {
        try {
            Desktop.getDesktop().browse(new URI(uri));
        } catch (IOException | URISyntaxException ex) {
            Logger.getLogger(ConfigInternalFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backupTab = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        salvarBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        taxaField = new javax.swing.JTextField();
        prazoLabel = new javax.swing.JLabel();
        prazoField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        BackupBtn = new javax.swing.JButton();
        RecoverLocalBackupBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        backupLabel = new javax.swing.JLabel();
        bkpDiario = new javax.swing.JCheckBox();
        RemoteBackupBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        footer = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        appVersion = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Configurações");

        salvarBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        salvarBtn.setText("Salvar Alterações");
        salvarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarBtnActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Empréstimos"));

        jLabel2.setText("Multa por dias de atraso ");

        taxaField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        taxaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                taxaFieldKeyReleased(evt);
            }
        });

        prazoLabel.setText("Prazo padrão para devolução (dias)");

        prazoField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        prazoField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                prazoFieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prazoLabel)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(taxaField, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                    .addComponent(prazoField))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(taxaField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prazoField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(prazoLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(salvarBtn)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salvarBtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 15, Short.MAX_VALUE))
        );

        backupTab.addTab("Preferências", jPanel2);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        BackupBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BackupBtn.setText("Realizar Backup Local");
        BackupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackupBtnActionPerformed(evt);
            }
        });

        RecoverLocalBackupBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RecoverLocalBackupBtn.setText("Restaurar Backup Local");
        RecoverLocalBackupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RecoverLocalBackupBtnActionPerformed(evt);
            }
        });

        jLabel3.setText("Último backup:");

        backupLabel.setText("jLabel4");

        bkpDiario.setSelected(true);
        bkpDiario.setText("Backup Diário ao Sair");
        bkpDiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bkpDiarioActionPerformed(evt);
            }
        });

        RemoteBackupBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RemoteBackupBtn.setText("Realizar Backup Online");
        RemoteBackupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoteBackupBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BackupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RemoteBackupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backupLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(bkpDiario))
                                .addGap(0, 49, Short.MAX_VALUE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(RecoverLocalBackupBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BackupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backupLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemoteBackupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bkpDiario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RecoverLocalBackupBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        backupTab.addTab("Dados e Backup", jPanel3);

        footer.setText("jLabel1");
        footer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                footerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                footerMouseEntered(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setText("JBiblioteca");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel1MouseEntered(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/jbiblioteca.png"))); // NOI18N

        appVersion.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        appVersion.setForeground(new java.awt.Color(51, 51, 51));
        appVersion.setText("jLabel5");
        appVersion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                appVersionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                appVersionMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(appVersion)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(footer)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(appVersion))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(footer)
                .addContainerGap())
        );

        backupTab.addTab("Sobre", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backupTab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(backupTab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void footerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_footerMouseClicked
        openBrowser("https://gabrieldewes.github.io");
    }//GEN-LAST:event_footerMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        openBrowser("https://gabrieldewes.github.io");
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseEntered
        jLabel1.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jLabel1MouseEntered

    private void footerMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_footerMouseEntered
        footer.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_footerMouseEntered

    private void prazoFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_prazoFieldKeyReleased
        salvarBtn.setEnabled(true);
    }//GEN-LAST:event_prazoFieldKeyReleased

    private void taxaFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_taxaFieldKeyReleased
        salvarBtn.setEnabled(true);
    }//GEN-LAST:event_taxaFieldKeyReleased

    private void salvarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarBtnActionPerformed
        String taxa = taxaField.getText();
        taxa = taxa.replaceAll(",", ".");
        String prazo = prazoField.getText();
        try {
            Double jurosAoDia = Double.valueOf(taxa);
            int prazoDefault = Integer.valueOf(prazo);
            try {
                if (configController.saveTaxaJuros(jurosAoDia)) {
                    String s = String.format("%1$,.2f", jurosAoDia);
                    taxaField.setText(""+s);
                    salvarBtn.setEnabled(false);
                    if (eif != null) {
                        EmprestimoInternalFrame.juros_dia = jurosAoDia;
                    }
                }
                if (configController.savePrazoDefault(prazoDefault)) {
                    prazoField.setText("" + prazoDefault);
                    salvarBtn.setEnabled(false);
                    if (eif != null) {
                        EmprestimoInternalFrame.prazo_default = prazoDefault;
                    }
                }
            } catch (Exception e1) {}
            
        }
        catch (NumberFormatException n) {
            // System.err.println("Exception "+n.getMessage());
            JOptionPane.showMessageDialog(null, "Campo numérico inválido.");
        }

    }//GEN-LAST:event_salvarBtnActionPerformed

    private void bkpDiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bkpDiarioActionPerformed
        configController.setAutoBackup(bkpDiario.isSelected());
    }//GEN-LAST:event_bkpDiarioActionPerformed

    private void RecoverLocalBackupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RecoverLocalBackupBtnActionPerformed
        
        RecoverLocalBackupBtn.setEnabled(false);
        int dialogResult = JOptionPane
                .showConfirmDialog (null, "Tem certeza que deseja substituir o banco de dados atual pelo último backup local?", 
                        "Recuperar Backup Local",
                        JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {

            if (DBUtil.recoverLocalBackup()) {
              JOptionPane.showMessageDialog(null, "O arquivo de backup local foi recuperado com êxito.");
            } else {
              JOptionPane.showMessageDialog(null, "Não foi encontrado o arquivo de backup local.");
            }
        }
        RecoverLocalBackupBtn.setEnabled(true);
        
    }//GEN-LAST:event_RecoverLocalBackupBtnActionPerformed

    private void BackupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackupBtnActionPerformed

        BackupBtn.setEnabled(false);
        int dialogResult = JOptionPane
                .showConfirmDialog (null, "Tem certeza que deseja substituir o último arquivo de backup local pelo banco de dados atual?", 
                        "Realizar Backup Local",
                        JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            
            if (DBUtil.backupDatabase()) {
                backupLabel.setText(configController.getLastBackupToString());
                JOptionPane.showMessageDialog(null, "O arquivo de backup local foi salvo com êxito.");
            } else {
                JOptionPane.showMessageDialog(null, "Não foi possível salvar o arquivo de backup local.");
            }   
        }
        BackupBtn.setEnabled(true);
    }//GEN-LAST:event_BackupBtnActionPerformed

    private void appVersionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appVersionMouseClicked
        openBrowser("https://github.com/gabrieldewes/JBiblioteca");
    }//GEN-LAST:event_appVersionMouseClicked

    private void appVersionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_appVersionMouseEntered
        appVersion.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_appVersionMouseEntered

    private void RemoteBackupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoteBackupBtnActionPerformed
       
        RemoteBackupBtn.setEnabled(false);
        int dialogResult = JOptionPane
                .showOptionDialog (null, 
                        "O backup remoto serve de garantia caso o seu computador apresente alguma falha ou esteja inoperável.\r\n\r\n" 
                        + "Antes de prosseguir, verifique se o computador possui uma conexão estável com a internet.", 
                        "Realizar Backup Online",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.INFORMATION_MESSAGE, 
                        null, 
                        new String[] { "Ok, prosseguir", "Não concordo, sair" },
                        "default");
        if (dialogResult == JOptionPane.YES_OPTION) {
            String translatedResult = DBUtil.remoteBackupDatabase();
            if (translatedResult != null) {
                JOptionPane.showMessageDialog(null, translatedResult);
            }
        }
        RemoteBackupBtn.setEnabled(true);
        
    }//GEN-LAST:event_RemoteBackupBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackupBtn;
    private javax.swing.JButton RecoverLocalBackupBtn;
    private javax.swing.JButton RemoteBackupBtn;
    private javax.swing.JLabel appVersion;
    private javax.swing.JLabel backupLabel;
    private javax.swing.JTabbedPane backupTab;
    private javax.swing.JCheckBox bkpDiario;
    private javax.swing.JLabel footer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField prazoField;
    private javax.swing.JLabel prazoLabel;
    private javax.swing.JButton salvarBtn;
    private javax.swing.JTextField taxaField;
    // End of variables declaration//GEN-END:variables
}