/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import control.TurmaController;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.OK_CANCEL_OPTION;
import javax.swing.JTextField;
import model.Turma;
import model.TurmaEnum;

/**
 *
 * @author Dewes
 */
public class TurmasInternalFrame extends javax.swing.JInternalFrame {

    /**
     * Creates new form TurmasGeralFrame
     */
    public TurmasInternalFrame() {
        initComponents();
        
        updateTableModel("");
    }
    
    private void updateTableModel(String buscar) {
        if (!"".equals(buscar)) {
            TurmaTable.setModel(TurmaController.ListarBusca(buscar));
        }
        else {
            TurmaTable.setModel(TurmaController.Listar());
        }
        TurmaTable.getColumnModel().getColumn(0).setMinWidth(0);
        TurmaTable.getColumnModel().getColumn(0).setPreferredWidth(0);
        TurmaTable.getColumnModel().getColumn(0).setMaxWidth(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        AddTurmaBtn = new javax.swing.JButton();
        anoField = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nomeField = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TurmaTable = new javax.swing.JTable();
        AttTurmaBtn = new javax.swing.JButton();
        DelTurmaBtn = new javax.swing.JButton();
        BuscaTurmaField = new javax.swing.JTextField();
        BuscaTurmaBtn = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Turmas");

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel6.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        AddTurmaBtn.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AddTurmaBtn.setText("Salvar");
        AddTurmaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTurmaBtnActionPerformed(evt);
            }
        });

        anoField.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        anoField.setModel(new DefaultComboBoxModel(TurmaEnum.values()));
        anoField.setBorder(null);

        jLabel1.setText("Nome");

        jLabel2.setText("Selecione o ano:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeField)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(anoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddTurmaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel1))
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(anoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddTurmaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("  Turmas  "));
        jPanel2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N

        TurmaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TurmaTable.getTableHeader().setReorderingAllowed(false);
        TurmaTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TurmaTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TurmaTable);

        AttTurmaBtn.setText("Alterar");
        AttTurmaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttTurmaBtnActionPerformed(evt);
            }
        });

        DelTurmaBtn.setText("Excluir");
        DelTurmaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DelTurmaBtnActionPerformed(evt);
            }
        });

        BuscaTurmaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                BuscaTurmaFieldKeyReleased(evt);
            }
        });

        BuscaTurmaBtn.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BuscaTurmaBtn.setText("Buscar");
        BuscaTurmaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaTurmaBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(BuscaTurmaField, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BuscaTurmaBtn)
                .addContainerGap(13, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(AttTurmaBtn)
                    .addComponent(DelTurmaBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BuscaTurmaField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BuscaTurmaBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(AttTurmaBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DelTurmaBtn)
                        .addGap(0, 84, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddTurmaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTurmaBtnActionPerformed
        String nome = nomeField.getText();
        String ano = anoField.getSelectedItem().toString();

        if (! "".equals(nome) ) {
            if (TurmaController.Salvar(nome, ano)) {
                nomeField.setText("");
                updateTableModel("");
            }
            else { JOptionPane.showMessageDialog(null, " Não foi possível salvar "+ nome +". Tente novamente"); }
        }
        else { JOptionPane.showMessageDialog(null, "Nome em branco. ", "Atenção", JOptionPane.WARNING_MESSAGE); }
    }//GEN-LAST:event_AddTurmaBtnActionPerformed

    private void DelTurmaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DelTurmaBtnActionPerformed
        int idx[] = TurmaTable.getSelectedRows();
        if (idx.length > 0) {
            int response = JOptionPane.showConfirmDialog(null, "Apagar "+ TurmaTable.getValueAt(TurmaTable.getSelectedRow(), 1) +"?", "Atenção",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (response == JOptionPane.YES_OPTION) {

                    int id = Integer.valueOf( TurmaTable.getValueAt( TurmaTable.getSelectedRow() , 0 ).toString() );
                    System.out.println("Botão mandou ID "+ id);
                    if (TurmaController.Apagar(id)) {
                        updateTableModel("");
                    }
                    else { JOptionPane.showMessageDialog(null, "Não foi possível excluir. Esta Turma possui Pessoas cadastradas! ", "Atenção", JOptionPane.WARNING_MESSAGE); }

            } 
        }
        else { DelTurmaBtn.setEnabled(false); }
        
        
    }//GEN-LAST:event_DelTurmaBtnActionPerformed

    private void BuscaTurmaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaTurmaBtnActionPerformed
        String str = BuscaTurmaField.getText();
        if (!"".equals(str)) {
            updateTableModel(str);
        }
        else updateTableModel("");
    }//GEN-LAST:event_BuscaTurmaBtnActionPerformed

    private void TurmaTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TurmaTableMouseClicked
        int idx[] = TurmaTable.getSelectedRows();
        if (idx.length > 0) {
            AttTurmaBtn.setEnabled(true);
            DelTurmaBtn.setEnabled(true);
        }
        else {
            AttTurmaBtn.setEnabled(false);
            DelTurmaBtn.setEnabled(false);
        }
    }//GEN-LAST:event_TurmaTableMouseClicked

    private void AttTurmaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttTurmaBtnActionPerformed
        int idx[] = TurmaTable.getSelectedRows();
        if (idx.length > 0) {
            JTextField nome = new JTextField();
            JComboBox<TurmaEnum> ano = new JComboBox();
            ano.setModel(new DefaultComboBoxModel( TurmaEnum.values() ));

            Object[] message = {
                "Nome:", nome,
                "Ano:", ano
            };
            int id = Integer.valueOf( TurmaTable.getValueAt( TurmaTable.getSelectedRow() , 0 ).toString() );
            Turma ex = TurmaController.Pegar(id);
            nome.setText( ex.getNome() );
            ano.setSelectedItem( TurmaEnum.get( ex.getAno() ) );

            int option=1;
            while (option != JOptionPane.OK_CANCEL_OPTION) {
                option = JOptionPane.showConfirmDialog(null, message, "Alterar turma", JOptionPane.OK_CANCEL_OPTION);
                if (option == JOptionPane.OK_OPTION) {  
                    
                    Turma t = new Turma(ex.getId_turma(), nome.getText(), ano.getSelectedItem().toString() );
                    if (! ex.equals(t)) {
                        if (TurmaController.Alterar(t)) {
                            updateTableModel("");
                            option = OK_CANCEL_OPTION;
                        }                     
                    }  
                    else 
                        option = OK_CANCEL_OPTION;                      
                }
                else option = OK_CANCEL_OPTION;

            }
        }
        else {AttTurmaBtn.setEnabled(false);}
    }//GEN-LAST:event_AttTurmaBtnActionPerformed

    private void BuscaTurmaFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_BuscaTurmaFieldKeyReleased
        String str = BuscaTurmaField.getText();
        if (!"".equals(str)) {
            updateTableModel(str);
        }
        else updateTableModel("");
    }//GEN-LAST:event_BuscaTurmaFieldKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTurmaBtn;
    private javax.swing.JButton AttTurmaBtn;
    private javax.swing.JButton BuscaTurmaBtn;
    private javax.swing.JTextField BuscaTurmaField;
    private javax.swing.JButton DelTurmaBtn;
    private javax.swing.JTable TurmaTable;
    private javax.swing.JComboBox<String> anoField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nomeField;
    // End of variables declaration//GEN-END:variables
}
